db_:
  dbType: postgres
  dbName: my_database
  dbUser: my_user
  dbPassword: my_password
  dbHost: localhost
  dbPort: 5432
  dbSchema: public
db:
  type: mysql
  name: saas
  user: root
  password: 123456
  host: localhost
  port: 3306
server:
  port: 8080
  host: 0.0.0.0

