db:
  type: postgres
  name: saas
  user: postgres
  password: 123456
  host: localhost
  port: 5432
 # dbSchema: public
db_:
  type: mysql
  name: saas
  user: root
  password: 123456
  host: localhost
  port: 3306
server:
  port: 8080
  host: 0.0.0.0

